# Generated by Django 4.0.5 on 2022-06-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
